### ISSUE TITLE
Présentation sur la landing page?

### ISSUE THREAD

**Issue by SamGuay** [CynthiaBH/dplyr-presentation#1]
Allô! 
Je vois que tu travailles activement sur ta présentation qui semble complète à première vue! Si jamais tu veux que ta présentation apparaisse à https://cynthiabh.github.io/dplyr-presentation/ au lieu de  https://cynthiabh.github.io/dplyr-presentation/dplyr_pres, tu n'as qu'à changer le nom de ton fichier HTML par `index.html`.
Laisse-moi savoir si tu as besoin d'un coup de main.

**Comment by SamGuay** [comment]
Autre suggestion: tu pourrais simplement indiquer l'URL de ta présentation dans le README, comme ça si un individu tombe sur cette page, il aurait accès à la présentation.

**Comment by CynthiaBH** [comment]
Merciiii, je cherchais justement comment tout ça :), j'essaie tout de suite

**Comment by CynthiaBH** [comment]
@SamGuay  j'ai changé le nom pour index.html, est-ce qu'il fallait faire autre chose ensuite ?

**Comment by SamGuay** [comment]
Tout semble fonctionner! :rocket:
